EBookLibrary/EBookLibrary.Presentation/Controllers/MVControllers/BookController.cs
using EBookLibrary.Client.Core.Implementations;
using EBookLibrary.DTOs.RatingDTOs;
using EBookLibrary.DTOs.ReviewDTOs;
using EBookLibrary.ViewModels;
using EBookLibrary.ViewModels.BookVMs;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Threading.Tasks;

namespace EBookLibrary.Presentation.Controllers.MVControllers
{
    public class BookController : Controller
    {
        private readonly IClientBookService _book;

        public BookController(IClientBookService book)
        {
            _book = book;
        }
        
        [HttpGet]
        public IActionResult AddBookView()
        {
            return View(new AddBook());
        }

        [HttpGet]
        public async Task<IActionResult> BookDetail(string id,  string message, bool? success)
        {
            var response = await _book.GetBook(id);
            if (!response.Success)
            {
                return RedirectToAction("ErrorHandler", "Error", new { statusCode = response.StatusCode});
            }
            /*if (response.Success is true)
            {
                return View(response.data);
            }
            return BadRequest();*/
            ViewBag.AddingSuccess = success;
            ViewBag.Message = message;
           
            return View(response.Data);
        }

        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public async Task<ActionResult> AddBookView(AddBook model)
        {
            var response = await _book.Add(model);
            if (response.Success is true)
            {
                return RedirectToAction("Admin", "Dashboard");
            }
            return BadRequest();
        }

        [HttpGet]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> UpdateMyBook(string id)
        {
            var data = await _book.GetBook(id);
            var model = new UpdateBookViewModel
            {
                Title = data.Data.Title,
                Author = data.Data.Author,
                Isbn = data.Data.Isbn,
                Pages =data.Data.Pages,
                Publisher = data.Data.Publisher,
                Category = data.Data.Category,
                Description = data.Data.Description,
                DatePublished = data.Data.DatePublished,
                Id = data.Data.Id,
                CopiesAvailable = data.Data.CopiesAvailable
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBooks([FromForm] string bookid)
        {
            var data = await _book.DeleteBook(bookid);
            return Redirect("/Dashboard/ManageBooks");
        }




        [HttpPost]
        public async Task<IActionResult> UpdateBooks(UpdateBookViewModel model, string Id)
        {
            if (ModelState.IsValid)
            {
                var response = await _book.UpdateBook(model, Id);
                if (response.Successful is true)
                {
                    ViewBag.Message = "Update Successful";
                    return RedirectToAction("ManageBooks","Dashboard");
                }
            }
            return BadRequest();
        }

        public async Task<IActionResult> Search(SearchParametersViewModel1 model)
        {
            if (string.IsNullOrEmpty(model.Query)) return Redirect("/");
            ViewBag.query = model.Query;
            var resp = await _book.Search(model);
            return View(resp);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePhoto( IFormFile avatar, string Id)
        {
            var uploadphotodtovm = new UploadPhotoVM
            {
                BookId = Id,
                BookPhoto = avatar
            };

            var response = await _book.UploadPhoto(uploadphotodtovm);
            if (response)
            {
                ViewBag.Message = "Update Successful";
                return View("successReg");
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> AddReview(GetBookDetailsResponseVM model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Wrong Review Format");
                return RedirectToAction("BookDetail", new { id = model.Id });
            }

            var userId = HttpContext.Session.GetString("Id");

            var reviewdto = new AddReviewDto
            {
                Comment = model.AddReviewVM.Comment,
                BookId = model.Id,
                UserId = userId
            };

            
            var res = await _book.AddReview(reviewdto);
            var message = "Review Added successfully";
            var success = true;
            if (!res)
            {

                success = false;
                message = "There was an error adding the review";

            }

            return RedirectToAction("BookDetail", new { id = model.Id, Success = success, Message = message });
        }

        [HttpPost]
        public async Task<IActionResult> AddRating(GetBookDetailsResponseVM model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Wrong Rating Format");
                return RedirectToAction("BookDetail", new { id = model.Id });
            }

            var userId = HttpContext.Session.GetString("Id");
            var ratingdto = new AddRatingDto
            {
                Ratings = model.AddRatingVM.Ratings,
                BookId = model.Id,
                UserId = userId
            };

            var res = await _book.AddRating(ratingdto);
            var message = "Rating Added Successfully";
            var success = true;

            if (!res)
            {
                //ModelState.AddModelError("", "Wrong Review Format");
                message = "There was an error adding the rating";
                success = false;
                //return RedirectToAction("BookDetail", new { id = model.Id });
            }
            
            return RedirectToAction("BookDetail", new { id = model.Id, Success = success, Message=message });
        }
    }
}

EBookLibrary/EBookLibrary.Presentation/Controllers/MVControllers/DashboardController.cs
using EBookLibrary.ViewModels.UserVMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EBookLibrary.Client.Core;
using EBookLibrary.Client.Core.Abstractions;
using EBookLibrary.ViewModels;
using EBookLibrary.Client.Core.Implementations;
using Microsoft.AspNetCore.Http;

namespace EBookLibrary.Presentation.Controllers.MVControllers
{
    public class DashboardController : Controller
    {
        private readonly IClientUserService _userService;
        private readonly IClientBookService _clientBookService;

        public DashboardController(IClientUserService userService,IClientBookService clientBookService)
        {
            _userService = userService;
            _clientBookService = clientBookService;
            
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var id = HttpContext.Session.GetString("Id");
            if (id == null) return Redirect("/account/login");
            var user = await _userService.GetUserById(id);

            if(user.Data.AvatarUrl == null)
            {
                user.Data.AvatarUrl = "~/images/dummyman.jpg";
            }

            return View(user.Data);
        }

        [HttpGet]
        public async Task<IActionResult> Admin(string id)
        {
            var totalNumOfUsers = await _userService.GetUsersCount();

            var totalNumOfBooks = await _clientBookService.GetBooksCount();

            var totalNumOfReviews = await _clientBookService.GetReviewsCount();

            var adminDashboardViewModel = new AdminDashboardViewModel
            {
                RegisteredUsers = totalNumOfUsers.Data,
                TotalBooks = totalNumOfBooks.Data,
                RecommendedReviews = totalNumOfReviews.Data
            };

            return View(adminDashboardViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ManageAccount(int PageNumber = 1, int PageSize = 5)
        {
            var model = new SearchParametersViewModel
            {
                PageNumber = PageNumber,
                PageSize = PageSize
            };
            var myUsers = await _userService.GetAllUser(model);

            return View(myUsers);
        }

        [HttpGet]
        public async Task<IActionResult> ManageBooks(int PageNumber =1, int PageSize = 5)
        {
            var model = new SearchParametersViewModel
            {
                PageNumber =PageNumber,
                PageSize = PageSize
            };
            var myBook = await  _clientBookService.Books(model);
            return View(myBook);
        }

        [HttpPost]
        public ActionResult UploadAvatar([FromForm] IFormFile avatar)
        {
            var Id = HttpContext.Session.GetString("Id");
            if (Id == null) return Redirect("/account/login");
            var model = new UploadUserAvatarViewModel
            {
                Avatar = avatar,
                UserId = Id
            };
            _userService.UploadPhoto(model);
            return RedirectToAction("Index");
        }
    }
}

EBookLibrary/EBookLibrary.Presentation/Controllers/MVControllers/UsersController.cs
using EBookLibrary.Client.Core.Abstractions;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EBookLibrary.Presentation.Controllers.MVControllers
{
    public class UsersController : Controller
    {

        private readonly IClientUserService _user;

        public UsersController(IClientUserService user)
        {
            _user = user;
        }



        public IActionResult Index()
        {
            return View();
        }

    

        [HttpPost]
        public async Task<IActionResult> DeleteUser([FromForm] string id)
        {
            var data = await _user.DeleteUser(id);
            return Redirect("/Dashboard/ManageAccount");
        }
    }
}

EBookLibrary/EBookLibrary.Presentation/Views/Dashboard/Admin.cshtml
@{
    Layout = "_DashboardLayout";
}
@model AdminDashboardViewModel


<section>
    <div class="row col-12 mb-4 pb-4 d-flex justify-content-center">
        <div class="card col-lg-3 col-sm-12 p-2 border-0 box-shadow myCard-Gradient1">

            <div class="card-body text-white">

                <div class="myCard-Title">
                    User Accounts <i class="fa fa-2x fa-chart-line float-right"> </i>
                </div>

                <span class="num">@Model.RegisteredUsers</span>
                <h5>Registered Users</h5>

            </div>


        </div>
        <div class="card col-lg-3 col-sm-12 p-2 offset-lg-1 border-0 box-shadow myCard-Gradient2">
            <div class="card-body text-white">
                <div class="myCard-Title">
                    Books   <i class="fa fa-2x fa-chart-pie float-right"> </i>
                </div>
                <span class="num">
                    @Model.TotalBooks
                </span>
                <h5>Total Books</h5>
            </div>
        </div>
        <div class="card col-lg-3 col-sm-12 p-2 offset-lg-1 border-0 box-shadow myCard-Gradient3">
            <div class="card-body text-white">
                <div class="myCard-Title">

                    Reviews  <i class="fa fa-2x fa-chart-bar float-right"> </i>

                </div>
                <span class="num ">
                    @Model.RecommendedReviews
                </span>
                <h5> Recommended Reviews</h5>
            </div>
        </div>

    </div>

</section>
<section>
    <div class="row col-12 mt-2 d-flex justify-content-center">
        <div class="card col-lg-6 col-sm-12 col-sm-12 p-2 border-0 box-shadow">

            <div class="card-body text-secondary">
                <div class="myCard-Title ">
                    Last Downloads
                    <hr />
                </div>



            </div>
        </div>
        <div class="card col-lg-4 offset-lg-1 col-sm-12 p-2 border-0 box-shadow">

            <div class="card-body text-secondary">
                <div class="myCard-Title">
                    Recent Reviews
                    <hr />
                </div>


            </div>
        </div>
    </div>
</section>

EBookLibrary/EBookLibrary.Presentation/Views/Dashboard/Index.cshtml
@{
    Layout = "_DashboardLayout";
}
@model UserDashboardViewModel
<!-- Page Content  -->
<div id="content">

    <div class="d-flex flex-row justify-content-center row ml-lg-2 mr-lg-5 pr-lg-3">
        <!--<div class="card col-lg-9 col-sm-12 border-0 bg-transparent userImgContaine">-->
        <div class="card col-lg-9 col-md-8 col-sm-12 border-0 bg-transparent userImgContaine mt-lg-5">
            <div class="card-header bg-secondary mt-lg-5">
                <h3 class="text-white">Your details</h3>
            </div>

            <div class="card-body">

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1" style="width:110px;"><b>First name</b></span>
                    </div>
                    <input type="text" class="form-control" value="@Model.FirstName" aria-label="First name" aria-describedby="basic-addon1" disabled>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1" style="width:110px;"><b>Last name</b></span>
                    </div>
                    <input type="text" class="form-control" value="@Model.LastName" aria-label="Last name" aria-describedby="basic-addon1" disabled>
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1" style="width:110px;"><b>Email</b></span>
                    </div>
                    <input type="text" class="form-control" value="@Model.Email" aria-label="Email" aria-describedby="basic-addon1" disabled>
                </div>

                <div class="line"></div>
            </div>
        </div>



        <!--<div class=" card col-lg-3 col-sm-12 box-shadow border-1 w-50 p-3 h-75">-->
            <div class="card col-sm-12 col-md-4 col-lg-3 box-shadow">
                <div class="text-center userImgContainer">
                    <img class="userImage card-img-top rounded-circle" asp-append-version="true" src="@Model.AvatarUrl" alt="image" width="250" height="300" />
                </div>
                <div class="card-body text-center">
                    <h6 class="text-secondary text-uppercase">
                        UserName
                    </h6>

                    <form method="post" enctype="multipart/form-data" asp-controller="Dashboard" asp-action="UploadAvatar">
                        <input type="file" name="avatar" id="avatar"/>
                        <button type="submit" class="btn btn-block btn-info">Upload photo</button>
                    </form>
                    
                </div>
            </div>
    </div>

</div>

EBookLibrary/EBookLibrary.Presentation/Views/Dashboard/ManageAccount.cshtml
@{
    Layout = "_DashBoardLayout";

}
@model EBookLibrary.DTOs.PagedResult<AdminUserViewModel> 

<div class="d-flex flex-row justify-content-around">
    <div class="col-lg-6 col-sm-6 p-sm-0 myCard-search">
        <div class="input-group text-center mb-3 box-shadow ">
            <input type="text" class="form-control"  placeholder="Search For User..." aria-label="Recipient's username" aria-describedby="basic-addon3">
            <input type="submit" class="input-group-text bg-primary pl-lg-4 pr-lg-4 " style="color:aliceblue;" id="basic-addon3" value="Search" />
        </div>
    </div>
</div>


<div class="d-flex flex-row justify-content-around">

    <div class="card col-lg-9 box-shadow border-0 p-4">

        <div class="card-header border-0">
            <h5>
                List Of Users
            </h5>

        </div>

        <div class="card-body">
            <table class="table table-borderless table-hover p-2">
                <thead>
                    <tr>
                        <th scope="col">Full Name</th>
                        <th scope="col">Email Address</th>
                        <th scope="col"> </th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.Result)
                    {
                        <tr>
                            <td>@item.FirstName @item.LastName</td>
                            <td>@item.Email</td>
                            <td class="justify-content-end">
                                <div class="btn-group" role="group" aria-label="">

                                    <form method="post" asp-action="DeleteUser" asp-controller="Users">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <input type="submit" value="Delete">
                                    </form>
                                </div>
                            </td>
                        </tr>
                      }
                </tbody>
                <tfoot>
                    <tr>
                        <td>

                            <div class="btn-group-lg">
                                <a class="btn-sm btn-primary" asp-route-pageSize="@Model.PageSize" asp-route-pagenumber="@Model.PreviousPage" aria-current="page"><i class="fa fa-angle-double-left"></i> Prev</a>
                                <a class="btn-sm btn-primary" asp-route-pageSize="@Model.PageSize" asp-route-pagenumber="@Model.NextPage"><i class="fa fa-angle-double-right"></i>Next</a>
                            </div>
                        </td>
                        <td>
                        </td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>


</div>

EBookLibrary/EBookLibrary.Presentation/Views/Dashboard/ManageBooks.cshtml
@{ Layout = "_DashboardLayout"; }
@model EBookLibrary.DTOs.PagedResult<BookCardViewModel>
<div class="d-flex flex-row justify-content-around">

    <div class="card col-lg-9 box-shadow border-0 p-4">

        <div class="card-header border-0">
            <h5>
                List Of Books <a class="btn-sm btn-outline-success float-right " asp-action="AddBookView" asp-controller="Book">Add Books</a>
            </h5>

        </div>

        <div class="card-body">
            <table class="table table-borderless table-hover p-2">
                <thead>
                    <tr>
                        <th scope="col">Book Title</th>
                        <th scope="col"> Author</th>
                        <th scope="col">SubCategory</th>
                        <th scope="col"> </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Result)
                    {

                        <tr>
                            <td>@item.Title</td>
                            <td>@item.Author</td>
                            <td>@item.Category</td>
                            <td class="justify-content-end">
                                <div class="btn-group" role="group" aria-label="">
                                   
                                        <a class="mr-3" asp-controller="Book" asp-action="UpdateMyBook" asp-route-id="@item.Id"><i class="fa fa-edit mr-2"></i></a>
                                    
                                        <form method="post" asp-action="DeleteBooks" asp-controller="Book">
                                            <input type="hidden" name="bookid" value="@item.Id" />
                                            <input type="submit" value="Delete" style="cursor:pointer;color:white; background:#0a0b4b; border: 0px solid transparent; padding:.3em; border-radius:.3em;">
                                        </form>


                                </div>
                            </td>
                        </tr>}
                </tbody>
                <tfoot>
                    <tr>
                        <td>

                            <div class="btn-group-lg">
                                <a  class="btn-sm btn-primary" asp-route-pageSize="@Model.PageSize" asp-route-pagenumber="@Model.PreviousPage" aria-current="page"><i class="fa fa-angle-double-left"></i> Prev</a>
                                <a class="btn-sm btn-primary" asp-route-pageSize="@Model.PageSize" asp-route-pagenumber="@Model.NextPage"><i class="fa fa-angle-double-right"></i>Next</a>
                            </div>
                        </td>

                    </tr>
                </tfoot>
            </table>
        </div>
    </div>


</div>